

[global]



[logger]


level = "info"


messageFormat = "%(asctime)s %(message)s"




[server]

folderWatchBlacklist = []


fileWatcherType = "auto"



headless = true


runOnSave = true


port = 8501

baseUrlPath = ""


enableCORS = true


enableXsrfProtection = true


maxUploadSize = 200


maxMessageSize = 200


enableWebsocketCompression = false


[browser]


serverAddress = "localhost"


gatherUsageStats = true


serverPort = 8501


[mapbox]


token = ""


[deprecation]


showfileUploaderEncoding = true


showPyplotGlobalUse = true


[theme]

primaryColor = "#f21111"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#31333F"
textColor = "#fafafa"
font = "sans serif"

